repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: local
    hooks:
      - id: pytest-check
        name: Tests
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
