repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [file, python]
      - id: ruff-lint
        name: ruff lint
        entry: ruff check --fix
        language: system
        types: [file, python]
      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        types: [file, python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [file, python]
        pass_filenames: false
