[tool.poetry]
name = "my_project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "my_project"}]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pre-commit = "^3.3.3"

[tool.pytest.ini_options]
addopts = "--cov=my_project"
testpaths = [
    "tests",
]
pythonpath = [
    "my_project",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
