name: CI

on:
  push:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.12", "3.13"]

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Rename project
        run: ./rename.sh my_project

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Ruff format
        run: uv run ruff format --check .

      - name: Ruff lint
        run: uv run ruff check --exit-non-zero-on-fix .

      - name: Mypy
        run: uv run mypy .

      - name: Tests
        run: uv run pytest
